server:
  port: 19080
spring:
  application:
    name: client-spring-cloud-spring-application-name
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka
spam:
  enabled: true
  timeout: 1_000
api:
  service:
    name: api-spring-cloud-spring-application-name
