server:
  port: 19080
spring:
  application:
    name: client-spring-cloud-spring-application-name
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:18761/eureka}
api:
  spam:
    enabled: true
  service:
    name: api-spring-cloud-spring-application-name