server:
  port: 18080
spring:
  application:
    name: api-spring-cloud-spring-application-name
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:18761/eureka}
