apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-spring-cloud-deployment
  labels:
    app: api-spring-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-spring-cloud
  template:
    metadata:
      labels:
        app: api-spring-cloud
    spec:
      containers:
        - name: api-spring-cloud
          image: api-spring-cloud
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-spring-cloud-service
spec:
  selector:
    app: api-spring-cloud
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
