services:
  eureka-spring-cloud:
    build:
      context: ../eureka-spring-cloud
      dockerfile: ../docker/java21.Dockerfile
    image: eureka-spring-cloud
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      retries: 10
      timeout: 1s
      interval: 1s
    environment:
      SERVER_PORT: 8080
    ports:
      - 18761:8080
  api-spring-cloud:
    build:
      context: ../api-spring-cloud
      dockerfile: ../docker/java21.Dockerfile
    image: api-spring-cloud
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/actuator/health" ]
      retries: 60
      timeout: 1s
      interval: 1s
    deploy:
      replicas: 3
    depends_on:
      eureka-spring-cloud:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: api-spring-cloud-spring-application-name
      DISCOVERY_SERVER_URL: http://eureka-spring-cloud:8080/eureka
      SPRING_PROFILES_ACTIVE: production
  client-spring-cloud:
    build:
      context: ../client-spring-cloud
      dockerfile: ../docker/java21.Dockerfile
    image: client-spring-cloud
    depends_on:
      eureka-spring-cloud:
        condition: service_healthy
      api-spring-cloud:
        condition: service_healthy
    ports:
      - 19080:8080
    environment:
      SERVER_PORT: 8080
      SPAM_ENABLED: false
      API_SERVICE_NAME: api-spring-cloud-spring-application-name
      DISCOVERY_SERVER_URL: http://eureka-spring-cloud:8080/eureka
      SPRING_PROFILES_ACTIVE: production
